"""add tg_id columns

Revision ID: 1f83569b16df
Revises: c0e1243cdbe6
Create Date: 2019-05-03 19:51:41.796740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f83569b16df'
down_revision = 'c0e1243cdbe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('tg_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('tg_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tg_id')
    op.drop_column('channels', 'tg_id')
    # ### end Alembic commands ###
